services:
  express-app:
    image: amelia16/express-app:latest
    ports:
      - "8080:8080"
    container_name: express-app

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=30
      - DOCKER_API_VERSION=1.44
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower